@echo off
REM ============================================================
REM  Remote Access Agent - Windows Installer
REM  
REM  This script automatically:
REM   1. Downloads FRP client
REM   2. Creates configuration
REM   3. Installs Windows Service
REM   4. Configures auto-restart on failure
REM   5. Starts the tunnel connection
REM
REM  Run as Administrator!
REM ============================================================

setlocal enabledelayedexpansion

REM ======================== CONFIGURATION ========================
REM VPS Server Settings (pre-configured for your relay server)
set "SERVER_ADDRESS=93.127.138.82"
set "SERVER_PORT=7000"
set "AUTH_TOKEN=36c2a86e0675e15c2f0fdbb107eec43d24bf5ea36c1aca3761ac2006f5a6f7e8"
set "REMOTE_PORT=33890"
set "RDP_PORT=3389"
set "API_BASE_URL=http://93.127.138.82:3000"

REM FRP Settings
set "FRP_VERSION=0.61.1"
set "INSTALL_DIR=C:\Program Files\RemoteAgent"
set "DATA_DIR=%ProgramData%\RemoteAgent"
set "LOG_DIR=%DATA_DIR%\Logs"
set "SERVICE_NAME=RemoteAccessAgent"
REM ===============================================================

title Remote Access Agent Installer

REM Check for admin privileges
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo  ERROR: This script must be run as Administrator!
    echo.
    echo  Right-click this file and select "Run as administrator"
    echo.
    pause
    exit /b 1
)

echo.
echo  ========================================================
echo       Remote Access Agent - Windows Installer
echo  ========================================================
echo.
echo  Server:      %SERVER_ADDRESS%:%SERVER_PORT%
echo  Remote Port: %REMOTE_PORT%
echo  Install Dir: %INSTALL_DIR%
echo.
echo  Press any key to begin installation...
pause >nul

REM ---- Step 1: Create Directories ----
echo.
echo  [1/7] Creating directories...
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"
if not exist "%DATA_DIR%" mkdir "%DATA_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
echo         Done.

REM ---- Step 2: Generate Device ID ----
echo  [2/7] Generating Device ID...
set "DEVICE_ID="
for /f "tokens=1-4 delims=- " %%a in ('wmic os get localdatetime /value ^| find "="') do (
    set "TIMESTAMP=%%a"
)
REM Use a combination of computer name and random number for device ID
set /a "RAND=%random%%random%"
set "DEVICE_ID=%COMPUTERNAME%-%RAND%"
REM Trim to 12 chars
set "DEVICE_ID=!DEVICE_ID:~0,12!"
echo         Device ID: %DEVICE_ID%

REM ---- Step 3: Download FRP Client ----
echo  [3/7] Downloading FRP client v%FRP_VERSION%...

set "FRP_ZIP=%TEMP%\frp_%FRP_VERSION%_windows_amd64.zip"
set "FRP_URL=https://github.com/fatedier/frp/releases/download/v%FRP_VERSION%/frp_%FRP_VERSION%_windows_amd64.zip"
set "FRP_EXTRACT=%TEMP%\frp_extract"

REM Try PowerShell download first
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri '%FRP_URL%' -OutFile '%FRP_ZIP%' -UseBasicParsing" 2>nul

if not exist "%FRP_ZIP%" (
    echo         ERROR: Failed to download FRP client.
    echo         Please check your internet connection.
    pause
    exit /b 1
)
echo         Downloaded successfully.

REM ---- Step 4: Extract FRP Client ----
echo  [4/7] Extracting FRP client...

if exist "%FRP_EXTRACT%" rmdir /s /q "%FRP_EXTRACT%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "Expand-Archive -Path '%FRP_ZIP%' -DestinationPath '%FRP_EXTRACT%' -Force" 2>nul

REM Find and copy frpc.exe
for /d %%D in ("%FRP_EXTRACT%\frp_*") do (
    copy /y "%%D\frpc.exe" "%INSTALL_DIR%\frpc.exe" >nul 2>&1
)

if not exist "%INSTALL_DIR%\frpc.exe" (
    echo         ERROR: Failed to extract FRP client.
    pause
    exit /b 1
)

REM Cleanup
del /f /q "%FRP_ZIP%" 2>nul
rmdir /s /q "%FRP_EXTRACT%" 2>nul
echo         Installed to %INSTALL_DIR%\frpc.exe

REM ---- Step 5: Create FRP Client Configuration ----
echo  [5/7] Creating FRP client configuration...

set "FRP_CONFIG=%DATA_DIR%\frpc.toml"
set "FRP_LOG=%DATA_DIR%\frpc.log"

REM Escape backslashes for TOML
set "FRP_LOG_ESCAPED=%FRP_LOG:\=\\%"

(
echo # FRP Client Configuration - Auto-generated by installer
echo # Do not edit manually.
echo.
echo serverAddr = "%SERVER_ADDRESS%"
echo serverPort = %SERVER_PORT%
echo.
echo auth.method = "token"
echo auth.token = "%AUTH_TOKEN%"
echo.
echo transport.protocol = "tcp"
echo transport.heartbeatInterval = 30
echo transport.heartbeatTimeout = 90
echo.
echo log.to = "%FRP_LOG_ESCAPED%"
echo log.level = "info"
echo log.maxDays = 7
echo.
echo [[proxies]]
echo name = "rdp-%DEVICE_ID%"
echo type = "tcp"
echo localIP = "127.0.0.1"
echo localPort = %RDP_PORT%
echo remotePort = %REMOTE_PORT%
) > "%FRP_CONFIG%"

echo         Configuration saved to %FRP_CONFIG%

REM ---- Step 6: Create and configure the launcher script ----
echo  [6/7] Setting up service launcher...

REM Create a launcher batch that the service/task will run
set "LAUNCHER=%INSTALL_DIR%\start-tunnel.bat"
(
echo @echo off
echo REM Remote Access Agent - FRP Tunnel Launcher
echo REM This script is run by Task Scheduler to maintain the tunnel
echo.
echo :loop
echo echo [%%date%% %%time%%] Starting FRP tunnel... ^>^> "%LOG_DIR%\launcher.log"
echo "%INSTALL_DIR%\frpc.exe" -c "%FRP_CONFIG%"
echo echo [%%date%% %%time%%] FRP tunnel disconnected. Restarting in 10 seconds... ^>^> "%LOG_DIR%\launcher.log"
echo timeout /t 10 /nobreak ^>nul
echo goto loop
) > "%LAUNCHER%"

REM Create a VBS wrapper to run hidden (no console window)
set "VBS_LAUNCHER=%INSTALL_DIR%\start-tunnel-hidden.vbs"
(
echo ' Remote Access Agent - Hidden Launcher
echo ' Runs the FRP tunnel without showing a console window
echo Set WshShell = CreateObject^("WScript.Shell"^)
echo WshShell.Run chr^(34^) ^& "%LAUNCHER%" ^& chr^(34^), 0, False
echo Set WshShell = Nothing
) > "%VBS_LAUNCHER%"

echo         Launcher scripts created.

REM ---- Step 7: Create Scheduled Task (runs at boot, auto-restart) ----
echo  [7/7] Creating scheduled task for auto-start...

REM Delete existing task if present
schtasks /delete /tn "%SERVICE_NAME%" /f >nul 2>&1

REM Create scheduled task that runs at system startup
schtasks /create /tn "%SERVICE_NAME%" /tr "wscript.exe \"%VBS_LAUNCHER%\"" /sc onstart /ru SYSTEM /rl HIGHEST /f >nul 2>&1

if %errorlevel% neq 0 (
    echo         WARNING: Could not create scheduled task.
    echo         Trying alternative method...
    schtasks /create /tn "%SERVICE_NAME%" /tr "wscript.exe \"%VBS_LAUNCHER%\"" /sc onlogon /rl HIGHEST /f >nul 2>&1
)

echo         Scheduled task created: %SERVICE_NAME%

REM ---- Start the tunnel now ----
echo.
echo  Starting tunnel connection...
echo.

REM Kill any existing frpc processes
taskkill /f /im frpc.exe >nul 2>&1
timeout /t 2 /nobreak >nul

REM Start the tunnel
start "" wscript.exe "%VBS_LAUNCHER%"
timeout /t 3 /nobreak >nul

REM Verify it's running
tasklist /fi "imagename eq frpc.exe" | find /i "frpc.exe" >nul 2>&1
if %errorlevel% equ 0 (
    echo  FRP tunnel is RUNNING!
) else (
    echo  WARNING: FRP tunnel may not have started correctly.
    echo  Check the log file: %DATA_DIR%\frpc.log
)

REM ---- Register device with API server ----
echo.
echo  Registering device with relay server...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "try { $body = @{deviceId='%DEVICE_ID%';authToken='%AUTH_TOKEN%';hostname=$env:COMPUTERNAME;remotePort=%REMOTE_PORT%} | ConvertTo-Json; $r = Invoke-RestMethod -Uri '%API_BASE_URL%/api/devices/register' -Method POST -Body $body -ContentType 'application/json' -TimeoutSec 10; if($r.success) { Write-Host '         Device registered successfully.' } else { Write-Host '         Note: ' $r.message } } catch { Write-Host '         Could not reach API server (tunnel-only mode).' }" 2>nul

REM ---- Summary ----
echo.
echo  ========================================================
echo       Installation Complete!
echo  ========================================================
echo.
echo  Device ID:       %DEVICE_ID%
echo  Server:          %SERVER_ADDRESS%:%SERVER_PORT%
echo  Remote RDP Port: %REMOTE_PORT%
echo  Install Dir:     %INSTALL_DIR%
echo  Config:          %FRP_CONFIG%
echo  Logs:            %DATA_DIR%\frpc.log
echo.
echo  The tunnel will automatically start when Windows boots.
echo.
echo  --------------------------------------------------------
echo  TO CONNECT REMOTELY:
echo    Open Remote Desktop and connect to:
echo    %SERVER_ADDRESS%:%REMOTE_PORT%
echo    Use this PC's Windows username and password.
echo  --------------------------------------------------------
echo.
echo  IMPORTANT: Make sure Remote Desktop is ENABLED on this PC:
echo    Settings ^> System ^> Remote Desktop ^> Enable
echo.
echo  To check tunnel status:
echo    Open %DATA_DIR%\frpc.log
echo.
echo  To stop the tunnel:
echo    taskkill /f /im frpc.exe
echo.
echo  To uninstall:
echo    Run Uninstall-RemoteAgent.bat as Administrator
echo.
pause
