using Microsoft.Extensions.Logging;
using RemoteAccessAgent.Models;

namespace RemoteAccessAgent.Tunnel;

/// <summary>
/// Generates FRP client configuration files (TOML format) for establishing
/// reverse tunnels through the relay server.
/// </summary>
public sealed class FrpConfigGenerator
{
    private readonly ILogger<FrpConfigGenerator> _logger;

    private static readonly string FrpConfigDirectory = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
        "RemoteAgent"
    );

    public FrpConfigGenerator(ILogger<FrpConfigGenerator> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Generates an FRP client TOML configuration file based on the agent configuration.
    /// Returns the path to the generated config file.
    /// </summary>
    public string GenerateConfig(AgentConfiguration config)
    {
        var configPath = Path.Combine(FrpConfigDirectory, "frpc.toml");

        if (!Directory.Exists(FrpConfigDirectory))
        {
            Directory.CreateDirectory(FrpConfigDirectory);
        }

        var tlsSection = config.EnableTls
            ? """
              
              [transport.tls]
              enable = true
              """
            : string.Empty;

        var configContent = $"""
            # FRP Client Configuration - Auto-generated by RemoteAccessAgent
            # Do not edit manually. Changes will be overwritten.

            serverAddr = "{config.ServerAddress}"
            serverPort = {config.ServerPort}

            [auth]
            method = "token"
            token = "{config.AuthToken}"

            [transport]
            protocol = "tcp"
            heartbeatInterval = {config.HeartbeatIntervalSeconds}
            heartbeatTimeout = 90
            {tlsSection}

            [log]
            to = "{EscapePath(Path.Combine(FrpConfigDirectory, "frpc.log"))}"
            level = "info"
            maxDays = 7

            [[proxies]]
            name = "rdp-{config.DeviceId}"
            type = "tcp"
            localIP = "127.0.0.1"
            localPort = {config.RdpPort}
            remotePort = {config.RemotePort}
            """;

        File.WriteAllText(configPath, configContent);
        _logger.LogInformation("FRP client configuration generated at {Path}", configPath);
        return configPath;
    }

    /// <summary>
    /// Escapes backslashes in file paths for TOML compatibility.
    /// </summary>
    private static string EscapePath(string path)
    {
        return path.Replace(@"\", @"\\");
    }
}
