#!/bin/bash
# ============================================================
# Remote Access Relay Server - Setup Script
# Tested on: Ubuntu 22.04 LTS
#
# This script installs and configures:
# - FRP Server (frps)
# - Node.js REST API for device management
# - Systemd services for auto-start
# - UFW firewall rules
# - TLS certificates (optional, via Let's Encrypt)
# ============================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
FRP_VERSION="${FRP_VERSION:-0.61.1}"
API_PORT="${API_PORT:-3000}"
FRP_BIND_PORT="${FRP_BIND_PORT:-7000}"
FRP_DASHBOARD_PORT="${FRP_DASHBOARD_PORT:-7500}"
INSTALL_DIR="/opt/remote-relay"
FRP_LOG_DIR="/var/log/frps"
NODE_VERSION="20"

echo -e "${CYAN}========================================"
echo " Remote Access Relay Server Setup"
echo -e "========================================${NC}"
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (sudo)${NC}"
    exit 1
fi

# Step 1: System update
echo -e "${YELLOW}[1/7] Updating system packages...${NC}"
apt-get update -qq
apt-get upgrade -y -qq
echo -e "${GREEN}  System updated${NC}"

# Step 2: Install Node.js
echo -e "${YELLOW}[2/7] Installing Node.js ${NODE_VERSION}...${NC}"
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
    apt-get install -y -qq nodejs
fi
echo -e "${GREEN}  Node.js $(node --version) installed${NC}"

# Step 3: Install FRP Server
echo -e "${YELLOW}[3/7] Installing FRP Server v${FRP_VERSION}...${NC}"
mkdir -p "$INSTALL_DIR" "$FRP_LOG_DIR"

FRP_ARCH="linux_amd64"
FRP_ARCHIVE="frp_${FRP_VERSION}_${FRP_ARCH}.tar.gz"
FRP_URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/${FRP_ARCHIVE}"

cd /tmp
if [ ! -f "$INSTALL_DIR/frps" ]; then
    wget -q "$FRP_URL" -O "$FRP_ARCHIVE"
    tar -xzf "$FRP_ARCHIVE"
    cp "frp_${FRP_VERSION}_${FRP_ARCH}/frps" "$INSTALL_DIR/"
    chmod +x "$INSTALL_DIR/frps"
    rm -rf "frp_${FRP_VERSION}_${FRP_ARCH}" "$FRP_ARCHIVE"
fi
echo -e "${GREEN}  FRP Server installed at ${INSTALL_DIR}/frps${NC}"

# Step 4: Configure FRP Server
echo -e "${YELLOW}[4/7] Configuring FRP Server...${NC}"

# Generate a random auth token if not provided
AUTH_TOKEN="${AUTH_TOKEN:-$(openssl rand -hex 32)}"
DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-$(openssl rand -hex 16)}"

cat > "$INSTALL_DIR/frps.toml" << EOF
# FRP Server Configuration - Auto-generated by setup script

bindAddr = "0.0.0.0"
bindPort = ${FRP_BIND_PORT}

auth.method = "token"
auth.token = "${AUTH_TOKEN}"

transport.tls.force = false

webServer.addr = "127.0.0.1"
webServer.port = ${FRP_DASHBOARD_PORT}
webServer.user = "admin"
webServer.password = "${DASHBOARD_PASSWORD}"

log.to = "${FRP_LOG_DIR}/frps.log"
log.level = "info"
log.maxDays = 30
EOF

echo -e "${GREEN}  FRP Server configured${NC}"
echo -e "${GREEN}  Auth Token: ${AUTH_TOKEN}${NC}"
echo -e "${GREEN}  Dashboard: http://localhost:${FRP_DASHBOARD_PORT} (admin/${DASHBOARD_PASSWORD})${NC}"

# Step 5: Set up API server
echo -e "${YELLOW}[5/7] Setting up REST API server...${NC}"
mkdir -p "$INSTALL_DIR/api"

# Copy API files
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../api/package.json" ]; then
    cp "$SCRIPT_DIR/../api/package.json" "$INSTALL_DIR/api/"
    cp "$SCRIPT_DIR/../api/server.js" "$INSTALL_DIR/api/"
else
    echo -e "${RED}  API files not found. Copy them manually to ${INSTALL_DIR}/api/${NC}"
fi

cd "$INSTALL_DIR/api"
npm install --production --silent 2>/dev/null || npm install --production
echo -e "${GREEN}  API server configured${NC}"

# Step 6: Create systemd services
echo -e "${YELLOW}[6/7] Creating systemd services...${NC}"

# FRP Server service
cat > /etc/systemd/system/frps.service << EOF
[Unit]
Description=FRP Server - Remote Access Relay
After=network.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/frps -c ${INSTALL_DIR}/frps.toml
Restart=always
RestartSec=5
LimitNOFILE=65536
StandardOutput=append:${FRP_LOG_DIR}/frps-stdout.log
StandardError=append:${FRP_LOG_DIR}/frps-stderr.log

[Install]
WantedBy=multi-user.target
EOF

# API Server service
cat > /etc/systemd/system/relay-api.service << EOF
[Unit]
Description=Remote Access Relay API Server
After=network.target frps.service
Wants=frps.service

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}/api
ExecStart=/usr/bin/node server.js
Environment=NODE_ENV=production
Environment=API_PORT=${API_PORT}
Environment=DB_PATH=${INSTALL_DIR}/api/data/relay.db
Restart=always
RestartSec=5
StandardOutput=append:/var/log/relay-api.log
StandardError=append:/var/log/relay-api-error.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable frps relay-api
systemctl start frps
systemctl start relay-api

echo -e "${GREEN}  Services created and started${NC}"

# Step 7: Configure firewall
echo -e "${YELLOW}[7/7] Configuring firewall...${NC}"

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
    apt-get install -y -qq ufw
fi

ufw allow 22/tcp comment "SSH"
ufw allow ${FRP_BIND_PORT}/tcp comment "FRP Server"
ufw allow 33800:34000/tcp comment "FRP Device Ports"
ufw allow ${API_PORT}/tcp comment "Relay API"

# Enable UFW if not already enabled
if ! ufw status | grep -q "Status: active"; then
    echo "y" | ufw enable
fi

echo -e "${GREEN}  Firewall configured${NC}"

# Save credentials
CREDS_FILE="$INSTALL_DIR/credentials.txt"
cat > "$CREDS_FILE" << EOF
============================================================
Remote Access Relay Server - Credentials
Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
============================================================

FRP Auth Token: ${AUTH_TOKEN}
FRP Dashboard: http://localhost:${FRP_DASHBOARD_PORT}
  Username: admin
  Password: ${DASHBOARD_PASSWORD}

API Server: http://$(hostname -I | awk '{print $1}'):${API_PORT}

IMPORTANT: Store these credentials securely and delete this file.
============================================================
EOF
chmod 600 "$CREDS_FILE"

# Summary
echo ""
echo -e "${CYAN}========================================"
echo " Setup Complete!"
echo -e "========================================${NC}"
echo ""
echo -e "FRP Server:     Running on port ${FRP_BIND_PORT}"
echo -e "API Server:     Running on port ${API_PORT}"
echo -e "FRP Dashboard:  http://localhost:${FRP_DASHBOARD_PORT}"
echo ""
echo -e "Auth Token:     ${AUTH_TOKEN}"
echo -e ""
echo -e "Credentials saved to: ${CREDS_FILE}"
echo ""
echo -e "${YELLOW}Service Commands:${NC}"
echo "  systemctl status frps"
echo "  systemctl status relay-api"
echo "  journalctl -u frps -f"
echo "  journalctl -u relay-api -f"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Note the Auth Token above"
echo "  2. On Windows PC, run the installer with this token"
echo "  3. Connect via RDP: <VPS_IP>:<assigned_port>"
echo ""
